version: "3.7"

services:
  redis:
    image: redis:latest
    container_name: redis
    restart: "unless-stopped"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 5
